name: Tag KLC Binaries

on:
  push:
    branches:
      - main
    paths:
      - VERSION

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Test
        run: go test ./...

      - run: |
          git tag -a -m "Release $(cat VERSION)" $(cat VERSION)
          git push origin $(cat VERSION)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
