package core

const (
	TokenUnknown        TokenKind = "unknown"
	TokenSynthetic      TokenKind = "synthetic"        // token generated by the compiler
	TokenEof            TokenKind = "eof"              // end of file token
	TokenComment        TokenKind = "comment"          // #
	TokenIndent         TokenKind = "indent"           // python-like indentation tokens
	TokenDedent         TokenKind = "dedent"           // python-like indentation tokens
	TokenSeparator      TokenKind = "separator"        // \n or ;
	TokenImport         TokenKind = "import"           // import
	TokenAssign         TokenKind = "assign"           // =
	TokenLeftParen      TokenKind = "left-paren"       // (
	TokenRightParen     TokenKind = "right-paren"      // )
	TokenComma          TokenKind = "comma"            // ,
	TokenIdentifier     TokenKind = "identifier"       // name
	TokenString         TokenKind = "string"           // 'hello' or "hello"
	TokenNumber         TokenKind = "number"           // 99, 3.14, 0xFF, 0o77, 0b11
	TokenHex            TokenKind = "hex"              // 0xFF
	TokenOct            TokenKind = "oct"              // 0o77
	TokenBin            TokenKind = "bin"              // 0b11
	TokenPlus           TokenKind = "plus"             // +
	TokenMinus          TokenKind = "minus"            // -
	TokenStar           TokenKind = "star"             // *
	TokenSlash          TokenKind = "slash"            // /
	TokenCaret          TokenKind = "caret"            // ^
	TokenPercent        TokenKind = "percent"          // %
	TokenGreater        TokenKind = "greater"          // >
	TokenGreaterEqual   TokenKind = "greater-equal"    // >=
	TokenLess           TokenKind = "less"             // <
	TokenLessEqual      TokenKind = "less-equal"       // <=
	TokenSpaceShip      TokenKind = "space-ship"       // <=>
	TokenEqual          TokenKind = "equal"            // ==
	TokenNotEqual       TokenKind = "not-equal"        // !=
	TokenAlmostEqual    TokenKind = "almost-equal"     // ~== (for floating-point comparisons)
	TokenAlmostNotEqual TokenKind = "almost-not-equal" // ~!= (for floating-point comparisons)
	TokenAnd            TokenKind = "and"              // and
	TokenOr             TokenKind = "or"               // or
	TokenXor            TokenKind = "xor"              // xor
	TokenBang           TokenKind = "bang"             // !
)

const (
	ErrorFile     ErrorKind = "file-error"
	ErrorSyntax   ErrorKind = "syntax-error"
	ErrorInternal ErrorKind = "internal-error"
)

var TokenKindMap = map[string]TokenKind{
	"#":      TokenComment,
	"import": TokenImport,
	"(":      TokenLeftParen,
	")":      TokenRightParen,
	"+":      TokenPlus,
	"-":      TokenMinus,
	"*":      TokenStar,
	"/":      TokenSlash,
	"^":      TokenCaret,
	"%":      TokenPercent,
	">":      TokenGreater,
	">=":     TokenGreaterEqual,
	"<":      TokenLess,
	"<=":     TokenLessEqual,
	"<=>":    TokenSpaceShip,
	"==":     TokenEqual,
	"!=":     TokenNotEqual,
	"~==":    TokenAlmostEqual,
	"~!=":    TokenAlmostNotEqual,
	"and":    TokenAnd,
	"or":     TokenOr,
	"xor":    TokenXor,
	"!":      TokenBang,
	"=":      TokenAssign,
}
