package core

const (
	TokenUnknown      TokenKind = "unknown"
	TokenSynthetic    TokenKind = "synthetic"     // token generated by the compiler
	TokenEof          TokenKind = "eof"           // end of file token
	TokenSpace        TokenKind = "space"         // spaces and tabs
	TokenComment      TokenKind = "comment"       // #
	TokenSeparator    TokenKind = "separator"     // newlines or ;
	TokenIndent       TokenKind = "indent"        // python-like indentation tokens
	TokenDedent       TokenKind = "dedent"        // python-like indentation tokens
	TokenImport       TokenKind = "import"        // import
	TokenAssign       TokenKind = "assign"        // =
	TokenLeftParen    TokenKind = "left-paren"    // (
	TokenRightParen   TokenKind = "right-paren"   // )
	TokenLeftBrace    TokenKind = "left-brace"    // {
	TokenRightBrace   TokenKind = "right-brace"   // }
	TokenIdentifier   TokenKind = "identifier"    // name
	TokenString       TokenKind = "string"        // 'hello' or "hello"
	TokenNumber       TokenKind = "number"        // 99, 3.14, xFF, o77, b11
	TokenHex          TokenKind = "hex"           // xFF
	TokenOct          TokenKind = "oct"           // o77
	TokenBin          TokenKind = "bin"           // b11
	TokenPlus         TokenKind = "plus"          // +
	TokenMinus        TokenKind = "minus"         // -
	TokenStar         TokenKind = "star"          // *
	TokenSlash        TokenKind = "slash"         // /
	TokenCaret        TokenKind = "caret"         // ^
	TokenPercent      TokenKind = "percent"       // %
	TokenGreater      TokenKind = "greater"       // >
	TokenGreaterEqual TokenKind = "greater-equal" // >=
	TokenLess         TokenKind = "less"          // <
	TokenLessEqual    TokenKind = "less-equal"    // <=
	TokenSpaceShip    TokenKind = "space-ship"    // <=>
	TokenEqual        TokenKind = "equal"         // ==
	TokenNotEqual     TokenKind = "not-equal"     // !=
	TokenAnd          TokenKind = "and"           // and
	TokenOr           TokenKind = "or"            // or
	TokenXor          TokenKind = "xor"           // xor
	TokenBang         TokenKind = "bang"          // !
)

const (
	ErrorFile     ErrorKind = "file-error"
	ErrorSyntax   ErrorKind = "syntax-error"
	ErrorInternal ErrorKind = "internal-error"
)

var TokenKindMap = map[string]TokenKind{
	"#":      TokenComment,
	"\n":     TokenSeparator,
	";":      TokenSeparator,
	"import": TokenImport,
	"{":      TokenLeftBrace,
	"}":      TokenRightBrace,
	"(":      TokenLeftParen,
	")":      TokenRightParen,
	"+":      TokenPlus,
	"-":      TokenMinus,
	"*":      TokenStar,
	"/":      TokenSlash,
	"^":      TokenCaret,
	"%":      TokenPercent,
	">":      TokenGreater,
	">=":     TokenGreaterEqual,
	"<":      TokenLess,
	"<=":     TokenLessEqual,
	"<=>":    TokenSpaceShip,
	"==":     TokenEqual,
	"!=":     TokenNotEqual,
	"and":    TokenAnd,
	"or":     TokenOr,
	"xor":    TokenXor,
	"!":      TokenBang,
	"=":      TokenAssign,
}
